#![windows_subsystem = "windows"]

use dashboard_core::app::DashboardApp;

// 64x64 RGBA window icon, generated by assets/make_icon.py (raw bytes, no
// decoder dependency needed).
const ICON_RGBA: &[u8] = include_bytes!("../assets/icon_64.rgba");
const ICON_SIZE: u32 = 64;

fn window_icon() -> egui::IconData {
    egui::IconData {
        rgba: ICON_RGBA.to_vec(),
        width: ICON_SIZE,
        height: ICON_SIZE,
    }
}

fn main() -> eframe::Result<()> {
    let viewport = egui::ViewportBuilder::default()
        .with_inner_size([1080.0, 720.0])
        .with_min_inner_size([820.0, 560.0])
        .with_title("Upkeep")
        .with_icon(window_icon());

    let native_options = eframe::NativeOptions {
        viewport,
        ..Default::default()
    };

    eframe::run_native(
        "Upkeep",
        native_options,
        Box::new(|cc| Ok(Box::new(DashboardApp::new(cc)))),
    )
}
